name: HarmonyHub
description: HarmonyHUB is your ONE source for information related to the Harmony Protocol.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.4.0
  http: ^0.12.0+4
  intl: ">=0.14.0"
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.4.3
  webview_flutter: ^0.3.22+1
  rflutter_alert: ^1.0.3
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^1.4.3
  google_fonts: ^1.1.0
  url_launcher: ^5.4.10
  twitter_api: ^0.1.2
  sqflite: ^1.3.0+1
  youtube_api: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
